### PR TITLE
22 bug fix team view

### LINKED ISSUE #22: 🐞 [Bug]: Fix `Team` view
### What happened?

Two things:

1. #### Information about the development team members isn't showing up in the Team view despite being set up in the `component_info` component.
    image of the bug

    This happens because the values are being incorrectly bound:
    Image
    Since the values that we want to bind are simply strings we shouldn't be using the `:` prefix, because if we use the prefix the expected value is a javascript object.

    To fix it either remove the binding prefix `:` or enclose the values in simple quotes.
    > **NOTE:** The `v-bind` prefix is not necessary either.

2. #### The view lacks responsiveness for small screen devices:

    Image

    I suggest the following:
    - Let's use `mdui` components to rebuild the view's elements, like the [card](https://www.mdui.org/en/docs/2/components/card) component, there are examples in the link.
    - We should make the whole card into a single component, currently we have a component called `component_info` that only contains the text of the card, seems silly to have a component only for that, it'd make more sense to have a component called something like `component_person_card`, that contains both the person's image and the person's information.

### Reproduction steps

```bash
1. Go to the site.
2. Open the side menu with the button on the top left corner of the screen.
3. Click on "Acerca de Lana Team".
4. See error
```

### What browsers are you seeing the problem on?

All of them

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Kolozuz**
# Change Details 

Make some tweaks in the `Team` view.

## Issues or Fixes 

See #22 for the detailed info

## Before merging branches 

- [ ] Reviewed by one or more developers on the team.

### CODE REVIEW

File: src/views/Team.vue [hunk 1]
```diff
@@ -1,43 +1,22 @@
...
-      <img src="@src/assets/1.jpg" alt="" class="image-profile">
-      <info :title="dsa" :text="dsad" :type="dsadsa" />
-    </div>
-    <div class="container">
-      <img src="@src/assets/104475729.png" alt="" class="image-profile">
-      <info :title="dsadsa" :text="dsadsa" :type="dsadasd" />
-    </div>
+    <person_card image="https://avatars.githubusercontent.com/u/110570465?v=4" title="Juan Pablo Morales Cruz" username="Kolozuz" link="https://github.com/Kolozuz" />
+    <person_card image="https://avatars.githubusercontent.com/u/108627976?v=4" title="Duvan Espinal Arboleda" username="DuvanArwenLazar" link="https://github.com/DuvanArwenLazar" />
+    <person_card image="https://avatars.githubusercontent.com/u/104475729?v=4" title="John Steban Lopez" username="JohnGolgota" link="https://github.com/JohnGolgota" />
```
Comment (JohnGolgota) [inline src/views/Team.vue]: Orient this to objects, it cannot be that a simple label is repeated...
...
...
...
what is this pr?

**Review by JohnGolgota — APPROVED** [review]
The above is a recommendation, because it's always better to use objects than to write the same thing three times.

File: src/views/Team.vue (hunk 1 above)
Comment (Kolozuz) [reply src/views/Team.vue]: Ok ok I agree, I'm a Vue noob tho so I'm not entirely sure how to approach it.

Maybe defining an object with all the info (names, usernames, urls) and then creating a single `person_card` tag and using a `v-for` to loop trough the object(?)
Is that what you mean, am I in the right track? Or am I just completely lost?

Comment (Kolozuz) [reply src/views/Team.vue]: > [!NOTE]
> @JohnGolgota Let me know if I'm on the right track and I'll make the change right away, before merging. 

Since I'm not very good at explaining myself with words, here's what I have in mind:
```vue
<template>
  <div class="team">
    <person_card v-for="dev in devs_info" :key="dev.id" :image="dev.image" :title="dev.name" :username="dev.username" :link="dev.link" />
  </div>
</template>

<script setup>
import person_card from "@src/components/component_person_card.vue";

const devs_info = [
  {
    id: 0,
    image: "https://avatars.githubusercontent.com/u/110570465?v=4",
    name: "Juan Pablo Morales Cruz",
    username: "Kolozuz",
    link: "https://github.com/Kolozuz"
  },
  {
    id: 1,
    image: "https://avatars.githubusercontent.com/u/108627976?v=4",
    name: "Duvan Espinal Arboleda",
    username: "DuvanArwenLazar",
    link: "https://github.com/DuvanArwenLazar",
  },
  {
    id: 2,
    image: "https://avatars.githubusercontent.com/u/104475729?v=4",
    name: "John Steban Lopez",
    username: "JohnGolgota",
    link: "https://github.com/JohnGolgota"
  }
]
;
</script>

<style scoped>
.team {
  display: flex;
  flex-wrap: wrap;
  gap: 1em;
  justify-content: center;
  animation: fadeInDown 1s;
}

</style>
```

Comment (JohnGolgota) [reply src/views/Team.vue]: yep 👍

**Review by JohnGolgota — APPROVED** [review]
zero complaints
